#https://fly.io/docs/app-guides/multiple-processes/#process-groups
# https://fly.io/docs/app-guides/global-nginx-proxy/
# https://github.com/DarthSim/overmind/blob/master/README.md?plain=1


app = 'apiserver-cold-mountain-8088'
primary_region = 'lhr'

[env]
ENV = "production"
AMQP_ENABLE = "1"
CACHING_SEC = "120"
APP_NAME = "TEST_testing"


[http_service]
processes = ["app"]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 0

[http_service.concurrency]
hard_limit = 10000
soft_limit = 7500
type = "connections"

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 2

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/health"
