#!/bin/bash

FLY_APP=mainnet_charts_server

export TERRAFORM_DIR="`dirname $0`/../.."
source $TERRAFORM_DIR/envs/mainnet/.env.charts_server # update


flyctl secrets -a  mainnet-charts-server set "ETH_PROVIDER=$ETH_PROVIDER" "WSS_PROVIDER=$WSS_PROVIDER" "CLOUDAMQP_URL=$CLOUDAMQP_URL" "DATABASE_URL=$DATABASE_URL" "MAINNET_DB=$MAINNET_DB" "MAINNET_ETH_PROVIDER=$MAINNET_ETH_PROVIDER" "ARBITRUM_DB=$ARBITRUM_DB" "ARBITRUM_ETH_PROVIDER=$ARBITRUM_ETH_PROVIDER" "OPTIMISM_DB=$OPTIMISM_DB" "OPTIMISM_ETH_PROVIDER=$OPTIMISM_ETH_PROVIDER"
