# fly.toml app configuration file generated for gearbox-ws on 2023-05-28T17:08:41+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gearbox-ws"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

#[deploy]
  #strategy = "canary"

[env]
# state engine
  #ADDRESS_PROVIDER = "0x95f4cea53121b8A2Cb783C6BFB0915cEc44827D3"
  ADDRESS_PROVIDER = "0x9ea7b04da02a5373317d745c1571c84aad03321d"
  ROLLBACK_MAX_BLOCK = "5"
# common
  AMQP_ENABLE = "1"
  APP_NAME = "TEST_gearbox-ws@H"
# application
  GB_VERSION_ALLOWED = "2"
  PORT = "8080"
  STORE_OLD_SNAPS = "1"
# fly
  PRIMARY_REGION = "ams"

# [[mounts]]
#   source="old_snaps"
#   destination="/app/data"
  
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[http_service.concurrency]
    hard_limit = 10000
    soft_limit = 7500
    type = "connections"

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/metrics"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512