#!/bin/bash

FLY_APP=gearbox-ws

TERRAFORM_DIR="`dirname $0`/../.."
source $TERRAFORM_DIR/envs/mainnet/.env.$FLY_APP

flyctl secrets -a $FLY_APP set "ETH_PROVIDER=$ETH_PROVIDER" "WSS_PROVIDER=$WSS_PROVIDER" "CLOUDAMQP_URL=$CLOUDAMQP_URL" "MAINNET_API_KEY=$MAINNET_API_KEY" "DB_URL=$DB_URL"
