# fly.toml app configuration file generated for charts-server on 2024-01-25T09:39:54+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bnb-charts-server"
primary_region = "ams"

[env]
ENV = "production"
AMQP_ENABLE = "1"
CACHING_SEC = "120"
#CS_STATUS="Maintenance in progress!"
APP_NAME = "TEST_bnb-charts_server"
APP_PORT = "[::]:8080"


[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

[http_service.concurrency]
hard_limit = 10000
soft_limit = 7500
type = "connections"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 512

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/health"
