# fly.toml app configuration file generated for gpointbot on 2023-09-02T14:02:44+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gpointbot"
primary_region = "ams"

[env]
  SQLITE_URL="db/local.db"
  APP_NAME="TEST_gpointbot"
  AMQP_ENABLE=true


[mounts]
  source = "gpointbot_vol"
  destination = "/app/db"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
 
[http_service]
  auto_stop_machines = false
