# fly.toml app configuration file generated for gpointbot on 2023-09-02T14:02:44+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gpointbot"
primary_region = "ams"

[env]
APP_NAME = "TEST_gpointbot"
AMQP_ENABLE = 1
ADDRESS_PROVIDER = "0x9ea7b04da02a5373317d745c1571c84aad03321d"
PORT = "8080"

[mounts]
source = "gpointbot_vol"
destination = "/app/db"


[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
