#!/bin/bash

FLY_APP=gpointbot
TERRAFORM_DIR="`dirname $0`/../.."
source $TERRAFORM_DIR/envs/mainnet/.env.$FLY_APP
flyctl secrets -a $FLY_APP set "BOT_TOKEN=$BOT_TOKEN" "CLOUDAMQP_URL=$CLOUDAMQP_URL" "MAINNET_ETH_PROVIDER=$MAINNET_ETH_PROVIDER" "MAINNET_WS_PROVIDER=$MAINNET_WS_PROVIDER"  "SQLITE_URL=$SQLITE_URL" "ARBITRUM_ETH_PROVIDER=$ARBITRUM_ETH_PROVIDER" "ARBITRUM_WS_PROVIDER=$ARBITRUM_WS_PROVIDER"  "SQLITE_URL=$SQLITE_URL" "ARBITRUM_EXPLORER_KEY=$ARBITRUM_EXPLORER_KEY"
