# fly.toml app configuration file generated for aggregatex on 2023-12-17T12:06:10+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aggregatex"
primary_region = "ams"

[env]
# cex prices
BINANCE_TOKENS = "UNI,1INCH,YFI,AAVE,DPI,COMP,LINK,SNX,LQTY,CVX,LDO,FXS,CRV,FEI,FRAX,SUSD,stETH,GUSD,USDT,LUSD,USDC,ETH,DAI,BTC"
NETWORKS = "ETH"
CYCLE_IN_SEC = "600"
BINANCE_URL = "https://www.binance.com/bapi/capital/v1/public/capital/getNetworkCoinAll?lang=en&ignoreDex=true"

#
APP_NAME = "TEST_Aggregatex@H"
AMQP_ENABLE = "1"
#
# for dex price
ADDRESS_PROVIDER = "0x9ea7b04da02a5373317d745c1571c84aad03321d"
ONEINCH_ORACLE = "0x07D91f5fb9Bf7798734C3f606dB065549F6893bb"
DEX_BASE_SYMBOL = "USDC"

# cex price
BINANCE_API_KEY = "4WJ6P3uczB5W0mEnZH9tv2sGvJiY2oEuJe4FW8HE21hupY9RQg8y88njPa0tb88z"
BINNACE_QUOTE_TOKEN = "USDT"
BINANCE_PRICE_FETCH_ONSTART = "true"
#
PORT = "8080"
[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256
