FLY_APP=aggregatex

TERRAFORM_DIR="`dirname $0`/../.."
source $TERRAFORM_DIR/envs/mainnet/.env.$FLY_APP

flyctl secrets -a $FLY_APP set "ETH_PROVIDER=$ETH_PROVIDER" "WSS_PROVIDER=$WSS_PROVIDER" "CLOUDAMQP_URL=$CLOUDAMQP_URL" "ETHERSCAN_API_KEY=$ETHERSCAN_API_KEY" "DATABASE_URL=$DATABASE_URL"