# fly.toml app configuration file generated for liquidator-v3 on 2023-12-18T18:03:31+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "liquidator-v3"
primary_region = "ams"

[env]
ROLLBACK_MAX_BLOCK = "5"
FLASHBOT_RPC = "https://rpc.flashbots.net/?hint=hash"
AMQP_ENABLE = "1"
APP_NAME = "TEST_LIQUIDATORV3@H"
ONE_INCH_BASE_API = "https://api.1inch.io/v5.0/1"
APP_PORT = "[::]:8080"
LIQ_THRESHOLD = "9995"
ETHERSCAN_DISABLED="true"
#
REDSTONE_PORT=8000
REDSTONE_URL="http://localhost:8000"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 512

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/metrics"
