# fly.toml app configuration file generated for deviator on 2023-06-26T19:32:11+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "deviator"
primary_region = "ams"

[env]
  APP_NAME="TEST_deviator"
  AMQP_ENABLE=true
  ONE_INCH_ORACLE="0x07D91f5fb9Bf7798734C3f606dB065549F6893bb"
  ADDRESS_PROVIDER="0xcF64698AFF7E5f27A11dff868AF228653ba53be0"
  PAUSER_ENABLE=false
  ONE_INCH_BASE_API="https://api.1inch.io/v5.0/1"
  ONE_INCH_QUOTE_AMOUNT="10000000000" # 10_000 USDC
  CHECK_TYPE="Chainlink" # Chainlink1InchAPI   Chainlink1Inch APIOracle1Inch

[experimental]
  allowed_public_ports = []
  auto_rollback = true
 
[http_service]
  auto_stop_machines = false
 
