# fly.toml app configuration file generated for trading-price on 2023-12-17T12:46:44+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "trading-price"
primary_region = "ams"

#[services.concurrency]
#hard_limit = 10000
#soft_limit = 7500
#type = "connections"

[env]
AMQP_ENABLE = "1"
APP_NAME = "TEST_TRADING_PRICE@H"
INCH_ORACLE = "0x07D91f5fb9Bf7798734C3f606dB065549F6893bb"
PORT = "8080"
[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[http_service.concurrency]
hard_limit = 10000
soft_limit = 7500
type = "connections"

[[http_service.checks]]
grace_period = "20s"
interval = "60s"
method = "GET"
timeout = "5s"
path = "/api/tradingview/config"

[[vm]]
cpu_kind = "shared"
cpus = 2
memory_mb = 3584
