#!/bin/bash

FLY_APP=trading_price

export TERRAFORM_DIR="`dirname $0`/../.."
source $TERRAFORM_DIR/envs/mainnet/.env.$FLY_APP


flyctl secrets -a  trading-price set "ETH_PROVIDER=$ETH_PROVIDER" "WSS_PROVIDER=$WSS_PROVIDER" "CLOUDAMQP_URL=$CLOUDAMQP_URL" "ETHERSCAN_API_KEY=$ETHERSCAN_API_KEY" "COINGLASS_API=$COINGLASS_API" "PRICE_DB=$PRICE_DB"  "ARBISCAN_API_KEY=$ARBISCAN_API_KEY" "OPTIMISM_API_KEY=$OPTIMISM_API_KEY" "MORALIS_API_KEY=$MORALIS_API_KEY"
