#!/bin/bash

FLY_APP=trading_price

export TERRAFORM_DIR="`dirname $0`/../.."
source $TERRAFORM_DIR/envs/mainnet/.env.$FLY_APP


flyctl secrets -a  trading-price set "ETH_PROVIDER=$ETH_PROVIDER" "WSS_PROVIDER=$WSS_PROVIDER" "CLOUDAMQP_URL=$CLOUDAMQP_URL" "COINGLASS_API=$COINGLASS_API" "PRICE_DB=$PRICE_DB"  "ARBITRUM_API_KEY=$ARBITRUM_API_KEY" "OPTIMISM_API_KEY=$OPTIMISM_API_KEY" "MORALIS_API_KEY=$MORALIS_API_KEY"


# flyctl secrets -a "MAINNET_API_KEY=$MAINNET_API_KEY" 