#!/bin/bash

FLY_APP=charts_server

export TERRAFORM_DIR="`dirname $0`/../.."
source $TERRAFORM_DIR/envs/mainnet/.env.$FLY_APP


flyctl secrets -a  charts-server set "ETH_PROVIDER=$ETH_PROVIDER" "WSS_PROVIDER=$WSS_PROVIDER" "CLOUDAMQP_URL=$CLOUDAMQP_URL" "DATABASE_URL=$DATABASE_URL" "OTEL_SERVICE_NAME=$OTEL_SERVICE_NAME" "OTEL_EXPORTER_OTLP_ENDPOINT=$OTEL_EXPORTER_OTLP_ENDPOINT" "OTEL_EXPORTER_OTLP_HEADERS=$OTEL_EXPORTER_OTLP_HEADERS" "MAINNET_DB=$MAINNET_DB" "MAINNET_ETH_PROVIDER=$MAINNET_ETH_PROVIDER" "ARBITRUM_DB=$ARBITRUM_DB" "ARBITRUM_ETH_PROVIDER=$ARBITRUM_ETH_PROVIDER" "OPTIMISM_DB=$OPTIMISM_DB" "OPTIMISM_ETH_PROVIDER=$OPTIMISM_ETH_PROVIDER"
